---
# name: .travis.yml
# description: This file tells travis, what needs to be done.
# author: while-true-do.io
# contact: hello@while-true-do.io
# license: BSD-3-Clause
# reference: https://docs.travis-ci.com/user/customizing-the-build

language: python
sudo: required
# Include supported python versions
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# services:
#
# env:
#
# before_install:
#
install:
  - scripts/tl-spelling.sh prep
  - scripts/tl-bash.sh prep
#
# before_script:
# Most likely, you want to put conf actions here
#
script:
  - scripts/tl-compliance.sh test
  - scripts/tl-spelling.sh test
  - scripts/tl-bash.sh test

# after_success:
#
# after_failure:
#
# before_deploy:
#
# deploy:
#
# after_deploy:
#
# after_script:
#

notifications:
  email:
    recipients:
      - devel@while-true-do.io
    on_success: never
    on_failure: always

  irc:
    channels:
      - "chat.freenode.net#while-true-do"
    on_success: always
    on_failure: always
